// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UCAKBİLETİ.Models;

#nullable disable

namespace UCAKBİLETİ.Migrations
{
    [DbContext(typeof(CustomerDBContext))]
    [Migration("20240810201652_ticket")]
    partial class ticket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UCAKBİLETİ.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerID"));

                    b.Property<int>("CustomerName")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerPass")
                        .HasColumnType("text");

                    b.HasKey("CustomerID");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("UCAKBİLETİ.Models.Flight", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlightID"));

                    b.Property<int>("FlightDataTime")
                        .HasColumnType("integer");

                    b.Property<string>("FlightTowhere")
                        .HasColumnType("text");

                    b.Property<int>("Flightquata")
                        .HasColumnType("integer");

                    b.Property<string>("Flightwhere")
                        .HasColumnType("text");

                    b.HasKey("FlightID");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("UCAKBİLETİ.Models.Reservation", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerID"));

                    b.Property<int>("CustomerID1")
                        .HasColumnType("integer");

                    b.Property<int>("DataTime")
                        .HasColumnType("integer");

                    b.Property<int>("FlightID")
                        .HasColumnType("integer");

                    b.Property<int>("Piece")
                        .HasColumnType("integer");

                    b.HasKey("CustomerID");

                    b.HasIndex("CustomerID1");

                    b.HasIndex("FlightID");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("UCAKBİLETİ.Models.Reservation", b =>
                {
                    b.HasOne("UCAKBİLETİ.Models.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("CustomerID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCAKBİLETİ.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("customer");
                });
#pragma warning restore 612, 618
        }
    }
}
